name: Build TDLib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Release/Debug/RelWithDebInfo)'
        required: true
        default: 'RelWithDebInfo'
      tdlib_version:
        description: 'TDLib version or branch'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout TDLib
      uses: actions/checkout@v2
      with:
        repository: tdlib/td
        ref: ${{ github.event.inputs.tdlib_version }}
        submodules: recursive

    - name: Cache vcpkg
      uses: actions/cache@v2
      env:
        cache-name: cache-vcpkg
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          !${{ github.workspace }}/vcpkg/buildtrees
          !${{ github.workspace }}/vcpkg/packages
          !${{ github.workspace }}/vcpkg/downloads
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Setup and build vcpkg
      env:
        VCPKG_MAX_CONCURRENCY: 4
      run: |
        if (!(Test-Path vcpkg)) {
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
        } else {
          cd vcpkg
        }
        ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows

    - name: Configure and Build TDLib
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      run: |
        Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
        mkdir build
        cd build
        cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }} ..
        cmake --build . --target install --config ${{ github.event.inputs.build_type }} --parallel 4

    - name: List TDLib files
      run: dir td/tdlib

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tdlib
        path: td/tdlib/**/*
